# Constants
{%- set OSU_MPI_IMAGE = "image-registry.openshift-image-registry.svc:5000/mpi-benchmarking/mpi-bench" %}
{%- set OSU_MPI_PATH = "/opt/osu-micro-benchmarks/libexec/osu-micro-benchmarks/mpi" %}

# Adjust the nproc value
{%- if operation == 'latency' or operation == 'bandwidth' %}
{%- set nproc = 2 %}
{%- endif %}

# Prepare the obj_name
{%- set obj_name = operation + "-" + nproc|string + "procs" %}

# Prepare the MPI command
{%- if operation == 'latency' %}
{%- set command = OSU_MPI_PATH + "/osu_latency" %}
{%- elif operation == 'bandwidth' %}
{%- set command = OSU_MPI_PATH + "/osu_bw" %}
{%- elif operation == 'osu-allreduce' %}
{%- set command = OSU_MPI_PATH + "/collective/osu_allreduce" %}
{%- elif operation == 'osu-alltoall' %}
{%- set command = OSU_MPI_PATH + "/collective/osu_alltoall" %}
{%- elif operation == 'hello' %}
{%- set command = "echo hello world" %}
{%- endif %}

---
apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: {{ obj_name }}
  namespace: {{ namespace }}
spec:
  sshAuthMountPath: /home/mpi/.ssh
  cleanPodPolicy: Running
  slotsPerWorker: 1
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          initContainers:
          - name: wait-hostfilename
            image: {{ OSU_MPI_IMAGE }}:base
            command:
            - bash
            - -cx
            - "[[ $(cat /etc/mpi/hostfile | wc -l) != 0 ]] && (date; echo 'Hostfile is ready'; cat /etc/mpi/hostfile) || (date; echo 'Hostfile not ready ...'; sleep 10; exit 1) && while read host; do while ! ssh $host echo $host ; do date; echo \"Pod $host is not up ...\"; sleep 10; done; date; echo \"Pod $host is ready\"; done <<< \"$(cat /etc/mpi/hostfile)\""
            volumeMounts:
            - mountPath: /etc/mpi
              name: mpi-job-config
            - mountPath: /home/mpi/.ssh
              name: ssh-auth
          containers:
          - name: mpi-launcher
            command:
            - mpirun
            #- -np
            #- "{{ nproc }}"
            - -bind-to
            - none
            - -map-by
            - slot
            - -mca
            - pml
            - ob1
            - -mca
            - btl
            - ^openib
            - bash
            - -c
            - {{ command }}
            image: {{ OSU_MPI_IMAGE }}:base
            imagePullPolicy: Always
    Worker:
      replicas: 4 # {{ nproc }}
      template:
        metadata:
          labels:
            app: {{ obj_name }}-worker
        spec:
          topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                app: {{ obj_name }}-worker
          containers:
          - name: mpi-worker
            image: {{ OSU_MPI_IMAGE }}:osu-bench
            imagePullPolicy: Always
          #nodeSelector:
            #node.kubernetes.io/instance-type: {{ machine }}
